#ifndef PROGRAM_CONFIG_H
#define PROGRAM_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define USB_CLOCK_RATE      48000000

#define PROGRAM_TASK_CNT 15
#define DEBUG_BUFFER 1024
//#define DEBUG_INFO_COUNT 20

#define EVENT_STACK_SIZE configMINIMAL_STACK_SIZE
#define EVENT_TASK_PRIO tskIDLE_PRIORITY + 2

#define POLL_STACK_SIZE configMINIMAL_STACK_SIZE
#define POLL_TASK_PRIO tskIDLE_PRIORITY + 2
#define POLL_TICK_MS  50

#define REPORT_STACK_SIZE configMINIMAL_STACK_SIZE
#define REPORT_TICK_MS 2000
#define REPORT_TASK_PRIO tskIDLE_PRIORITY + 2

#define USB_STACK_SIZE configMINIMAL_STACK_SIZE
#define USB_TASK_PRIO tskIDLE_PRIORITY + 5

#define SPK_CODEC_STACK_SIZE configMINIMAL_STACK_SIZE
#define SPK_CODEC_TASK_PRIO tskIDLE_PRIORITY + 7

#define MIC_CODEC_STACK_SIZE (3*configMINIMAL_STACK_SIZE)
#define MIC_CODEC_TASK_PRIO tskIDLE_PRIORITY + 7

#define CH_STACK_SIZE configMINIMAL_STACK_SIZE
#define CH_TASK_PRIO tskIDLE_PRIORITY + 6

#define CDC_STACK_SIZE configMINIMAL_STACK_SIZE
#define CDC_TASK_PRIO tskIDLE_PRIORITY + 3

#define DISPLAY_STACK_SIZE     (3*configMINIMAL_STACK_SIZE)
#define DISPLAY_TASK_PRIO tskIDLE_PRIORITY + 1
#define DISPLAY_TICK_MS  100

#ifdef __cplusplus
}
#endif

#endif /*PROGRAM_CONFIG_H*/
